package br.com.condominio.feature.role;

public enum PermissionCode {
  USER_VIEW,
  USER_MANAGE,
  REGISTRATION_VIEW,
  REGISTRATION_APPROVE,
  RESIDENCE_PROOF_VIEW,
  CONTACT_MANAGE,
  LINK_MANAGE,
  FAQ_MANAGE,
  TAG_MANAGE,
  RECOMMENDATION_MODERATE,
  CLASSIFIED_MODERATE,
  ROLE_ASSIGN,
  PERMISSION_GRANT,
  AUDIT_VIEW
}
