management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    br.com.condominio: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
